#!/bin/sh
set -eu
case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            deb-systemd-invoke --user stop vremoter-linux.service atvvoice.service || true
        fi
        ;;
esac
